# Generated by Django 5.1.1 on 2024-10-23 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('status_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='status_name',
        ),
        migrations.AddField(
            model_name='user',
            name='gpt_key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='gamification.category'),
        ),
    ]
