# Generated by Django 5.1.1 on 2024-12-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_key',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
