# Generated by Django 5.1.1 on 2025-01-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_user_gpt_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gpt_key',
            field=models.CharField(max_length=100),
        ),
    ]
